name: yumnotes
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  sizer: ^2.0.15
  audioplayers:
  flutter_sound:
  flutter_polyline_points:
  hive_flutter:
  hive:
  flutter_stripe:
  google_mobile_ads:
  anim_search_bar: ^2.0.3
  flutter_rating_bar: ^4.0.1
  google_maps_flutter: ^2.2.6
  location:
  flutter_google_places:
  fluttertoast:
  charts_flutter:
  google_maps_webservice:
  image:
  google_place:
  url_launcher:
  auto_size_text:
  firebase_auth:
  firebase_core:
  firebase_storage:
  cloud_firestore:
  google_sign_in:
  image_picker:
  restart_app:
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  build_runner: ^2.0.6
  hive_generator: ^1.1.1
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/mainLogo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

